Feat/dark mode
obytes/react-native-template-obytes pull request #158
Opened 2023-05-05 12:29 UTC by 0x1337ak

## What does this do?

apply dark mode style 

## How did you test this?

Locally Manually Android IOS

2023-05-10 00:05 UTC, yjose commented
@0x10Ayoub i did some refactoring to make the process more easy to use. 
One thing you need to complete here is to add theme logic for navigator and not for every screen, check [docs here ](https://reactnavigation.org/docs/themes/)

also look like you forgot to update the login screen as well as bottom sheet title

2023-05-10 00:05 UTC, yjose requested changes
looks good so far, check my comment

2023-05-11 13:45 UTC, yjose commented
Looks good with the new colors, but the onboarding screen still isn't working correctly with the dark theme @0x10Ayoub

2023-05-11 13:48 UTC, yjose requested changes
Looks good with the new colors, but the onboarding screen still isn't working correctly with the dark theme @0x10Ayoub

2023-05-11 14:12 UTC, 0x10Ayoub commented
@yjose Thanks I totally forgot it.

2023-05-11 17:08 UTC, yjose requested changes

2023-05-11 17:08 UTC, yjose commented on src/navigation/hooks.tsx
I prefer using use-theme-config.tsx as file name

2023-05-11 17:08 UTC, yjose commented on src/navigation/navigation-container.tsx
> +  theme,
not sure why you need to pass theme from the parent, you can use hook instead

2023-05-11 17:08 UTC, yjose commented on src/screens/onboarding/cover.tsx
Why svg instead of a simple image ?

2023-05-11 17:10 UTC, 0x10Ayoub commented on src/navigation/hooks.tsx
yes i did refactor it

2023-05-11 17:11 UTC, 0x10Ayoub commented on src/screens/onboarding/cover.tsx
@0x10Ayoub  to make it compatible with  the  dark mode

2023-05-11 17:14 UTC, yjose commented on src/screens/onboarding/cover.tsx
ok

2023-05-11 17:15 UTC, 0x1337ak commented on src/screens/onboarding/cover.tsx
it doesn't look good in dark mode half white screen half black screen

2023-05-11 17:18 UTC, 0x10Ayoub commented on src/navigation/navigation-container.tsx
> +  theme,
i want to make it  clear where we pass theme props

2023-05-11 18:01 UTC, yjose requested changes
here is some comments, also  you forgot to mention how to switching from dark, light, system theme is done, you need to add it

2023-05-11 18:01 UTC, yjose commented on docs/docs/ui-and-theme/ui-theming.mdx
> +```ts
Import files directly and show the content. Take a look at other files to see how you can do that.

2023-05-11 18:01 UTC, yjose commented on docs/docs/ui-and-theme/ui-theming.mdx
> +### How dark mode works
How it work and implementation are the same thing isn't , keep implementation

2023-05-11 18:01 UTC, yjose commented on docs/docs/ui-and-theme/ui-theming.mdx
> +### Why dark mode ?
you need to mention that the template comes with a resolution to support dark mode, using tailwindcss after you mentioned the important of having a dark mode in your app

2023-05-11 18:01 UTC, yjose commented on docs/docs/ui-and-theme/ui-theming.mdx
> +To implement the dark mode, you typically define two sets of color palettes and Since we’re using nativewind and react-navigation we let theme handle applying it ,and  we just take care of the colors
The way you are phrasing your sentences is like you are trying to teach them how they can do it(they dont need to add any thing everything is already done) . You need to explain how it has been implemented in the starter so they can understand what going on behind the scene

2023-05-11 18:01 UTC, yjose commented on docs/docs/ui-and-theme/ui-theming.mdx
> +to add values for light mode you can simple write them direlty in your component class and for dark mode you can use the dark: variant
here you can teach them 😀 nice 
also you can refere to nativewind and tailwind css doc about dark mode

2023-05-11 18:01 UTC, yjose commented on docs/docs/ui-and-theme/ui-theming.mdx
> +if you want to use style prop you can use the useColorScheme hook to get the current color scheme and use it to apply the style you want
mention that for most of the case, you will not need that, and dark: variant should work for most of the cases

2023-05-11 18:01 UTC, yjose commented on src/core/hooks/index.tsx
> +export * from './use-theme-config';
this file is related to navigation, please put  it to navigation folder

2023-05-12 11:04 UTC, 0x10Ayoub commented on src/navigation/navigation-container.tsx
> +  theme,
@yjose what do you think about this 👆

2023-05-15 10:11 UTC, yjose requested changes
One last thing, please make sure to fix capitalization while starting a new sentence and add the following video at the beginning of the Dark Mode section to showcase the feature.

https://github.com/obytes/react-native-template-obytes/assets/11137944/37620367-b639-417e-a802-c48a3d7566ba

2023-05-15 12:04 UTC, yjose approved these changes

2023-05-15 12:05 UTC, merged