Fix/fixes
obytes/react-native-template-obytes pull request #287
Opened 2024-03-21 10:01 UTC by ElenaBitire

## What does this do?

 - fix issues related to web support 
 - fix template always being RTL despite the app being English when local is an Arabic country
 - fix background color for Select's options 

## How did you test this?

 - locally

2024-03-21 15:19 UTC, yjose commented on src/core/i18n/index.tsx
> -  lng: getLanguage() || locale,
@ElenaBitire  Hmmm, I am not sure if this is the right way. We are using locale in case your phone is Arabic so we can load the correct language based on your settings. What I would suggest is to keep it as it is and add the comment  below:

```
lng: getLanguage() || locale, // TODO: if you are not supporting multiple languages or languages with multiple directions you can set the default value to `en`
```

2024-03-21 15:19 UTC, yjose commented on src/ui/select.test.tsx
> +import '@shopify/flash-list/jestSetup';
I think it should be added to the test-util file?

2024-03-21 15:26 UTC, yjose commented on src/ui/select.tsx
> +        <List
@ElenaBitire **BottomSheetFlatList** is important here, as it is linked to the bottom sheet modal logic and can handle gestures much better than other lists.

I would suggest continuing to use BottomSheetFlatList and using FlatList on the web.

```js
// create a list component 
const List = Platform.OS === 'web' ? FlatList : BottomSheetFlatList 
// then you can use it, I suppose they have the same typing definition 
```

2024-03-21 21:36 UTC, yjose requested changes

2024-03-21 21:36 UTC, yjose commented on src/ui/select.tsx
> +    const List = Platform.OS === 'web' ? FlashList : BottomSheetFlatList;
Should be outside the component

2024-03-29 17:40 UTC, hamzamekk commented
is Nativewind 4 the source of issue in Windows ?

Upon encountering the issue mentioned in the GitHub [link](https://github.com/obytes/react-native-template-obytes/issues/289), which was reported by a user facing problems on Windows, I realized I could replicate the scenario since I also have a Windows system. To address the issue, I embarked on a debugging journey. However, the absence of clear error messages made it challenging to pinpoint the root cause, especially considering our template's complex library dependencies.

To investigate further, I conducted a test by creating two projects—one with the Expo router and another without. Surprisingly, both projects functioned smoothly, particularly on the web platform. Encouraged by this, I decided to integrate nativewind version 4 into both projects, following the [provided instructions](https://www.nativewind.dev/v4/getting-started/react-native).

Unexpectedly, upon integration, both projects encountered the same issue observed in our template—getting stuck on the terminal during the bundling process. This recurrence strongly suggested that nativewind 4 might be the underlying cause of the problem.

In an attempt to validate this hypothesis, I delved deeper into research and came across discussions indicating potential issues with the Metro config file. However, removing it did run all three projects but not really sure what's going on behind the scene and for our template it didn't really run due to compatibility with web for several libs.

In conclusion, the problem seems to be closely associated with the configuration of nativewind 4.

2024-03-29 17:47 UTC, yjose commented
Thank you @hamzamekk for your time, can you please check if this fix https://github.com/marklawlor/nativewind/pull/854 is working as expected

2024-03-29 18:23 UTC, hamzamekk commented
> Thank you @hamzamekk for your time, can you please check if this fix [marklawlor/nativewind#854](https://github.com/marklawlor/nativewind/pull/854) is working as expected

you're welcome, and for the solution it's working perfectly

2024-03-29 18:32 UTC, yjose commented
Thank you @hamzamekk 🙏
@ElenaBitire  We will wait until the PR is merged to NativeWind, and then we can merge this PR as well.

2024-03-29 18:42 UTC, ElenaBitire commented
> Thank you @hamzamekk 🙏 @ElenaBitire We will wait until the PR is merged to NativeWind, and then we can merge this PR as well.

Sure @yjose and thank you very much @hamzamekk for taking your time! 🙏

2024-03-29 18:45 UTC, hamzamekk commented
Thank you @yjose @ElenaBitire my pleasure to help 👌👌

2024-03-29 20:16 UTC, dmitryshostak commented
I've mentioned the nativewind's creator to merge the fix ASAP. https://github.com/marklawlor/nativewind/pull/860 Hoping he'll respond soon. Blocking us a little as well.

Btw, it's the first time I see `react-native-template-obytes` - splendid job, guys! Your stack is almost identical to ours 👍 ❤️

2024-03-30 18:53 UTC, tonven commented
Hi. I noticed that this line is commented out in your template: https://github.com/obytes/react-native-template-obytes/blob/b894d276ad9a03d82fcee8ddc0bf8a365aa96d27/src/core/hooks/use-selected-theme.tsx#L36
So this means it will not load current theme from mmkv on app restart / web refresh. Is it supposed to be like this? Thanks :smile:

2024-03-30 21:33 UTC, yjose commented
Nice catch @tonven , I remember commenting on this line as the function was not exported correctly from nativewind. I opened a PR to Nativewind to fix this and it was already merged, i updated it in our internal projects but forgot to update it here

2024-04-02 11:27 UTC, ElenaBitire commented
We are going to merge this PR since it contains other fixes but the [issue](https://github.com/obytes/react-native-template-obytes/issues/289) related to web support on Windows system remains open.

2024-04-02 11:29 UTC, merged