feat: add dynamic params to text
obytes/react-native-template-obytes pull request #384
Opened 2024-11-08 11:32 UTC by elalami-m

## What does this do?

This PR extends the `Text` component to support translation parameters by modifying the `tx` prop to accept an object with a translation key and parameters. This allows developers to use dynamic, interpolated values within translations (e.g., inserting names or numbers into strings).

## Why did you do this?

This change was made to improve the flexibility of the `Text` component, particularly for internationalization. In many cases, translations require dynamic content (e.g., greetings with a user’s name), and this update allows developers to pass those parameters directly through the component. It simplifies the code needed for multi-language support and enhances readability.

## Who/what does this impact?

This change impacts developers using the `Text` component for localized content, as it enables dynamic translations without requiring custom workarounds. This is especially relevant for teams working on multilingual applications that need flexibility in handling text. It should not introduce any breaking changes to existing functionality, as it maintains backward compatibility with the previous `tx` prop type.

## How did you test this?

- Verified that the `Text` component correctly renders static translations as before.
- Tested the component with translations that include dynamic parameters, ensuring they render as expected.
- Checked the component in RTL and LTR layouts to confirm no side effects with the added parameter support.

2024-11-08 11:57 UTC, yjose requested changes
Sounds good, but can we ensure we add the correct type for the option to avoid using `any`?

Also the name `params` is a bit misleading, i would prefer using `options` instead

2024-11-08 13:37 UTC, elalami-m commented
Thank you for the feedback, @yjose! 🙏

I’ve updated the code to replace any with a more specific type ({ [key: string]: string }) for the options. I also renamed params to options as you suggested to improve clarity.

Let me know if there’s anything else I can adjust.

2024-11-08 15:07 UTC, yjose commented
@elalami-m Good! I would love to make the option more accurate by adding the correct type. I think it should be `TranslateOptions`. You can check this [file](https://github.com/obytes/react-native-template-obytes/blob/master/src/core/i18n/utils.tsx).

2024-11-09 12:03 UTC, yjose commented
@elalami-m I would also appreciate it if you could add an example for translations as part of the style screen, similar to what we have for typography and buttons. By providing the different values available for text with translation and options, we can enhance clarity.

2025-01-24 00:06 UTC, closed without merging